In [ ]:
# day 11
#      foundation of ai
# scalar - 0 dimensional value eg: 5
# vector
# linear algebra - 1 dimensional value eg: [1,2,3,4,5]

#scalar=4 
# vector- 1 deimension value eg:[1,2,3,4,5]
# matrix- 2 or more diemensional value eg: [[1,2],[2,3]] 
# tensor- 3 or more dimensional value eg: [[[1,2],[2,3]],[[1,2],[2,3]]]


In [2]:
import numpy as np
scalar=5
vector=np.array([1,2,3,4,5])
matrix=np.matrix([[1,2,2],[3,2,1],[1,2,3]])
print(scalar)
print(vector.ndim)
print(matrix.ndim)
print(np.linalg.matrix_rank(matrix))
# tensor- 3 or more dimensional value eg: [[[1,2],[2,3]],[[1,2],[2,3]]]

5
1
2
3


In [3]:
# dot product of two vectors using numpy

row=np.array([1,2,3])
col=np.matrix([[1],[2],[3]])
print(row.ndim) #ndim - it returns number of dimensions (1D, 2D, etc.  )
print(col.ndim)
print(row)
print(col)

1
2
[1 2 3]
[[1]
 [2]
 [3]]


In [4]:
# multiply of two vectors using numpy
v1=np.array([[1,2],[3,4]])
v2=np.array([[1,2],[3,4]])
print(v1*v2)
print(2*v1)

[[ 1  4]
 [ 9 16]]
[[2 4]
 [6 8]]


In [5]:
# dot product of two vectors using numpy
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
result = np.dot(A, B)
print(result)

[[ 7 10]
 [15 22]]


In [6]:
#transpose of a matrix
v1=np.array([[1,2],[3,4]])
print(v1.T)

[[1 3]
 [2 4]]


In [7]:
# cross product of two vectors
# The cross product is only defined for 3-dimensional vectors.
import numpy as np


A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
result = np.cross(A, B)
print(result)

[0 0]


C:\Users\hp\AppData\Local\Temp\ipykernel_4356\4086599768.py:8: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  result = np.cross(A, B)


In [8]:
# dot product of two vectors
# The dot product is defined for vectors of the same dimension.


A = np.array([1, 2,3, 4])
B = np.array([1, 2,3, 4])
result = np.dot(A, B)
print(result)

30


In [9]:
# cross product of two vectors
# The cross product is only defined for 3-dimensional vectors.
import numpy as np
A = np.array([[1, 2,3], [7,9,6]])
B = np.array([[4,5,6], [9,5,6]])
result = np.cross(A, B)
print(result)

[[ -3   6  -3]
 [ 24  12 -46]]


In [10]:
# dot product of two vectors using a for loop

a=[1,2,3]
b=[4,5,6]
c=0
for i in range(len(a)):
    c+=(a[i]*b[i])  
print(c)    

32


In [11]:
# transpose of a matrix using a for loop
# This code transposes a matrix by swapping rows and columns.

a=[[1, 2, 3],[4, 5, 6]]
b=[]
for i in range(len(a[0])): # loop through columns
    c=[]
    for j in range(len(a)): # loop through rows
        c.append(a[j][i])
    b.append(c)

print("transpose of a matrix is:")    

for d in b:
    print(d)
   

transpose of a matrix is:
[1, 4]
[2, 5]
[3, 6]
